# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='img',
            field=models.ImageField(default='none', upload_to=b''),
            preserve_default=False,
        ),
    ]
