# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='title',
        ),
        migrations.AddField(
            model_name='publication',
            name='citation',
            field=models.TextField(default=datetime.datetime(2016, 9, 25, 16, 37, 4, 98973, tzinfo=utc), max_length=2000, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.DateField(),
        ),
    ]
