# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20160925_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(default=2016),
        ),
    ]
