# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20160925_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000, unique=True)),
                ('year', models.IntegerField(default=2016)),
            ],
        ),
    ]
