# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 18:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 25, 18, 10, 15, 501331)),
        ),
    ]
