# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20160925_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='year',
            new_name='date',
        ),
    ]
